Fix shellcheck SC2230 error (#1074)
Fix shellcheck SC2230 error

ansible-test-sanity-docker-devel fails:
ERROR: Found 2 shellcheck issue(s) which need to be resolved:
ERROR: tests/integration/targets/inventory_vmware_host_inventory/runme.sh:5:72: SC2230: which is non-standard. Use builtin 'command -v' instead.
ERROR: tests/integration/targets/inventory_vmware_vm_inventory/runme.sh:5:72: SC2230: which is non-standard. Use builtin 'command -v' instead.

This doesn't hurt because it's non-voting. However, I'd prefer it to succeed.
It looks like shellcheck wants us to replace which with command -v so I'd like to give this a try.

Reviewed-by: None <None>