vmware_host_lockdown: VmwareLockdownManager object has no attribute warn (#1540)
vmware_host_lockdown: VmwareLockdownManager object has no attribute warn

SUMMARY
Fix AttributeError: 'VmwareLockdownManager' object has no attribute 'warn' in vmware_host_lockdown.
ISSUE TYPE

Bugfix Pull Request

COMPONENT NAME
vmware_host_lockdown
ADDITIONAL INFORMATION

  
    
      community.vmware/plugins/modules/vmware_host_lockdown.py
    
    
         Line 152
      in
      9ed1182
    
  
  
    

        
          
           self.warn("'present' will be removed in a future version. Please use 'normal' instead.") 
        
    
  



  
    
      community.vmware/plugins/modules/vmware_host_lockdown.py
    
    
         Line 155
      in
      9ed1182
    
  
  
    

        
          
           self.warn("'absent' will be removed in a future version. Please use 'disabled' instead.")